In [112]:
# TO DO
# clean up order date
# clean up free trial
# clean up access to (fill blanks and date only)
# clean up termination date (fill blanks and date only)
# solve for FTP conversion y/n

import pandas as pd
import json
from datetime import datetime

order_data = pd.read_csv('order_data.csv')
orders = order_data

In [113]:
orders['order_date_date'] = orders['order_date']

orders.head()

,customerid,signup_date,subscription_type,order_date,free_trial_period,purchase_device,access_from,access_to,first_bill_date,content_type,...,termination_comment,days_active_from_bill_2,months_rounded_up,active,cancelled_in_first_7days,termination_clean_dates,failedpayment_code,failedpayment_desc,ga_user_hash,order_date_date
0,351,10/29/15 17:58:01,SUBSCRIPTION,10/29/15 18:00:25,NaN,Web,10/29/15 18:00:25,NaN,10/29/2015,BUNDLE_PURCHASE,...,NaN,371,13,True,False,01/01/2020,NaN,NaN,756E69766973696F6E6E6F77333531,10/29/15 18:00:25
1,352,10/30/15 11:29:08,SUBSCRIPTION,10/30/15 11:29:30,7.0,Web,10/30/15 11:29:30,11/06/15 00:00:01,11/06/2015,BUNDLE_PURCHASE,...,Notified termination at 11/06/2015:QA test,-1,1,False,True,11/05/2015,NaN,NaN,756E69766973696F6E6E6F77333532,10/30/15 11:29:30
2,353,10/30/15 11:30:01,SUBSCRIPTION,10/30/15 11:30:38,7.0,Web,10/30/15 11:30:38,11/06/15 00:00:01,11/06/2015,BUNDLE_PURCHASE,...,Notified termination at 11/06/2015:QA test,-1,1,False,True,11/05/2015,NaN,NaN,756E69766973696F6E6E6F77333533,10/30/15 11:30:38
3,354,10/30/15 11:31:49,SUBSCRIPTION,10/30/15 11:32:40,NaN,Web,10/30/15 11:32:41,11/30/15 00:00:01,10/30/2015,BUNDLE_PURCHASE,...,Notified termination at 11/30/2015:QA test,6,1,False,False,11/05/2015,NaN,NaN,756E69766973696F6E6E6F77333534,10/30/15 11:32:40
4,355,10/30/15 11:42:42,SUBSCRIPTION,10/30/15 11:43:31,NaN,Web,10/30/15 11:43:34,11/30/15 00:00:01,10/30/2015,BUNDLE_PURCHASE,...,Notified termination at 11/30/2015:QA test,6,1,False,False,11/05/2015,NaN,NaN,756E69766973696F6E6E6F77333535,10/30/15 11:43:31

In [115]:
# removing time from the order_date_date field
def extract(row):
    return row[0:8]

orders.order_date_date = orders.order_date_date.apply(extract)

orders.head()

,customerid,signup_date,subscription_type,order_date,free_trial_period,purchase_device,access_from,access_to,first_bill_date,content_type,...,termination_comment,days_active_from_bill_2,months_rounded_up,active,cancelled_in_first_7days,termination_clean_dates,failedpayment_code,failedpayment_desc,ga_user_hash,order_date_date
0,351,10/29/15 17:58:01,SUBSCRIPTION,10/29/15 18:00:25,NaN,Web,10/29/15 18:00:25,NaN,10/29/2015,BUNDLE_PURCHASE,...,NaN,371,13,True,False,01/01/2020,NaN,NaN,756E69766973696F6E6E6F77333531,10/29/15
1,352,10/30/15 11:29:08,SUBSCRIPTION,10/30/15 11:29:30,7.0,Web,10/30/15 11:29:30,11/06/15 00:00:01,11/06/2015,BUNDLE_PURCHASE,...,Notified termination at 11/06/2015:QA test,-1,1,False,True,11/05/2015,NaN,NaN,756E69766973696F6E6E6F77333532,10/30/15
2,353,10/30/15 11:30:01,SUBSCRIPTION,10/30/15 11:30:38,7.0,Web,10/30/15 11:30:38,11/06/15 00:00:01,11/06/2015,BUNDLE_PURCHASE,...,Notified termination at 11/06/2015:QA test,-1,1,False,True,11/05/2015,NaN,NaN,756E69766973696F6E6E6F77333533,10/30/15
3,354,10/30/15 11:31:49,SUBSCRIPTION,10/30/15 11:32:40,NaN,Web,10/30/15 11:32:41,11/30/15 00:00:01,10/30/2015,BUNDLE_PURCHASE,...,Notified termination at 11/30/2015:QA test,6,1,False,False,11/05/2015,NaN,NaN,756E69766973696F6E6E6F77333534,10/30/15
4,355,10/30/15 11:42:42,SUBSCRIPTION,10/30/15 11:43:31,NaN,Web,10/30/15 11:43:34,11/30/15 00:00:01,10/30/2015,BUNDLE_PURCHASE,...,Notified termination at 11/30/2015:QA test,6,1,False,False,11/05/2015,NaN,NaN,756E69766973696F6E6E6F77333535,10/30/15